### PR TITLE
Do not leak bits of local environment into various places

### PR DESCRIPTION
**Pull request by intelfx**
* do not leak `IFS=$'\0'` into the callback (set it when needed and unset immediately afterwards)
* do not clobber global `line` (make it local)

### CODE REVIEW

**Comment by mafredri** [comment]
Thanks for this! Under what circumstances does `IFS` leak into the cb? Do you think we could use `local -h IFS=$'\0'` (hidden) instead?

**Comment by mafredri** [comment]
Actually, reading the docs it seems it should perhaps be `local +h IFS=$'\0'`.

> It is also possible to create a local parameter using ‘typeset +h special’, where the local copy of special will retain its special properties regardless of having the -h attribute.

**Comment by intelfx** [comment]
I can't see how `typeset -h` helps.

When we declare a `local IFS=$'\0'` in `async_process_results()` and then call cb from this scope, the cb inherits `IFS=$'\0'` which may break its logic.

**Comment by mafredri** [comment]
I think you're right. I was not aware that a callee would inherit a local variable like this. I created a simple test script for this and spotted what might be a potential edge case using `local/unset` like this: `IFS` will always be unset for the callback as well, even if it is globally set to something else.

I propose we rewrite it as: 

```zsh
() {
	local IFS=$'\0'
	items=("${(@)=ASYNC_PROCESS_BUFFER[$worker]}")
	unset IFS
}
```

^an anonymous, immediately invoked function with a local scope that will not interfere with anything else. Thoughts?

PS. I still wonder if `local +h IFS=$'\0'` is better than just `local IFS=$'\0'`. Don't know enough about this though to make that call.

---

This is what I used for a test:

```zsh
#!/usr/bin/env zsh
IFS="a"
typeset -p IFS
child() {
	print "child"; typeset -p IFS
}
parent() {
	print "parent"
	# () {
	typeset IFS="b"; typeset -p IFS; unset IFS
	# }
	child
}
parent
```

**Comment by intelfx** [comment]
> IFS will always be unset for the callback as well, even if it is globally set to something else.

Wow, I did not know about this. I assumed bash behavior when unsetting a local variable reintroduces the one from parent scope.

Then yes, an anonymous function will do. I'll force-push.

Using `local +h IFS` is only needed protect against a `typeset -h IFS` in global scope, but I don't know whether it is feasible; there are probably many more ways for a user to break their environment.

**Comment by mafredri** [comment]
Ah yeah, no need to unset with the anon function, good catch! This is great, big thanks! :)

**Pull request merged**
