### PR TITLE
Implement async_worker_eval to affect environment inside worker

### LINKED ISSUE #25: Async jobs should inherit PWD and all environment variables
The life would be _much simpler_ if jobs could inherit all environment variables and current directory from the parent. Currently one has to remember to pass all needed information via job arguments, and that is very annoying, easy to forget and takes time to find out.

[Example in pure prompt](https://github.com/sindresorhus/pure/blob/2e4879390e9ae7c7a1c945628b5faaefd25827c9/pure.zsh#L209-L210) — this should have been done by zsh-async itself.

I'm asking because people are catching bugs like "forgot to `cd` in proper folder", or "`$PATH` is missing some folders", and such bugs will keep coming unless we fix this once and for all in the framework (https://github.com/maximbaz/spaceship-prompt/pull/3)

### PR DESCRIPTION
**Pull request by mafredri**
Based on #27 by @annacrombie.

Closes #25.
Closes #27.

### CODE REVIEW

**Comment by mafredri** [comment]
Haha, thanks @maximbaz 😄.

**Comment by annacrombie** [comment]
I can't test this at the moment, but I'd say everything looks good to me.  I wanted to implement this too but was too worried about getting tripped up by strange shell expansions.

**Comment by mafredri** [comment]
Thanks for the feedback @maximbaz and @annacrombie. 

> I wanted to implement this too but was too worried about getting tripped up by strange shell expansions.

I feel ya 😄! At least this uses much of the same code path as `async_job` so if there's an issue it needs to be fixed in both.

I'll go ahead and release this, please report back if you run into any issues!

**Comment by annacrombie** [comment]
@mafredri, I finally got around to testing this, and just a little thing I noticed: The cat coproc is spawned before the eval occurs so cat does not inherit the environment, which isn't acceptable for my use case.  I easily got around this by just reorganizing the code a little as you can see [here](https://github.com/mafredri/zsh-async/compare/master...annacrombie:upstream).  I wonder if this messes anything else up, or perhaps it is only me who would need this behaviour.  Anyways I thought I would let you know.

**Comment by annacrombie** [comment]
As soon as I updated, I was noticing this problem. With 60fa536, the issue was partially fixed, the first change of directory would be propogated but future changes were not.  This was happening wether or not I did `async_flush_jobs`.  I was able to finally fix this by just killing the coproc before any "async eval" operation took place.  See [here](https://github.com/mafredri/zsh-async/compare/master...annacrombie:upstream-fix).  I am not really sure why async_flush_jobs wasn't working but this isn't something I wanted to spend too much time on.  I'm not really recommending that you include my patches, I'm just letting you know in case there is something interesting to you.

**Pull request merged**
